import '../output.css'

export const metadata = {
  title: 'Frontend Mentor',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className='
          overflow-x-hidden
          flex
          flex-col
          min-h-screen
        '
      >
        <main
          className='
            flex
            flex-col
            grow
            max-w-7xl
            pt-16
            px-8
            mx-auto
          '
        >
          {children}
        </main>
      </body>
    </html>
  )
}
